// <auto-generated />
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Data.Migrations
{
    [DbContext(typeof(ExamplesDbContext))]
    partial class ExamplesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PhrasalVerb.Domain.Example", b =>
                {
                    b.Property<long>("ExampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ExampleId"));

                    b.Property<string>("ExampleFull")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExampleFullUnderscore")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExampleParticle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExampleVerb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Verb")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VerbAndParticle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExampleId");

                    b.HasIndex("ExampleId")
                        .IsUnique();

                    b.ToTable("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
